### ISSUE TITLE
Cannot write LinSpace

### ISSUE THREAD

**Issue by mwil** [fhs/NPZ.jl#16]
In Julia v0.5 the output type of the `linspace()` function has been changed to `LinSpace`, which is not a subtype of `Array`, but of `AbstractArray`. Because of this, it is not seamlessly possible to write the output of `linspace()` and similar functions. 
```bash
> NPZ.npzwritearray("test.npz", linspace(1,2))
ERROR: MethodError: no method matching npzwritearray(::String, ::LinSpace{Float64})
```
It works when you explicitly `convert` it to `Array`, but wouldn't it be better to change the signature of `npzwritearray()` to accept `AbstractArray`?

**Comment by fhs** [comment]
I think this has been fixed by https://github.com/fhs/NPZ.jl/commit/0bd3fbfe3b37b4dbcbc531a72da4e878f66a7292
