### ISSUE TITLE
UndefVarError in line 116 of NPZ.jl

### ISSUE THREAD

**Issue by tomosoeoc** [fhs/NPZ.jl#35]
Hello,

Here is the line 115-117 of NPZ.jl.

```
        if s[tail_idx] == 'L' # output of firstindex should be a valid code point

            tail_idx = nextind(s, i)

        end
```

`i` in `nextind(s, i)` is not defined in this function, and results in an UndefVarError. I encountered this while running `npzread` with julia-1.3.0 on Windows 10.

Thanks!

**Comment by galenlynch** [comment]
Sorry :(
